apiVersion: v1
kind: Service
metadata:
  name: backend-jonas-zubieta-service
  namespace: jonas-zubieta-namespace
spec:
  type: NodePort
  ports:
  - port: 30001
    targetPort: 8080
    nodePort: 30001
  selector:
    app: backend-jonas-zubieta-deployment